---
title: "cleaning"
format: html
---

```{r}
#create tibble for data cleaning
team_info <- tibble(info = teams)

#clean up full team name, add age group and state column. 
team_info |>
  mutate(team_name = str_squish(info),
    age_group = str_extract(team_name, "[0-9]{2}u$"),
    state = str_extract(team_name, "(?<=\\().*?(?=\\))")) -> beverly_bandits
```

```{r}
#create links to be scraped for coach information. 
#correct format is "https://thebeverlybandits.com/team/premierorfutures-coachlastname-agegroup-state/coaches

beverly_bandits |>
  mutate(level = str_extract(team_name, "Futures|Premier"),
         coaches = str_extract(team_name, "[\\w/]+(?=\\s*\\d+u)"),
         coaches = str_replace_all(coaches, "/", "-"),
         coach_link = str_glue("https://thebeverlybandits.com/team/{level}-{coaches}-{age_group}-{state}/coaches"),
         coach_link = tolower(coach_link))|>
  select(-info)-> coach_links
```

```{r}
#clean coach information
coach_df = tibble(info = coach_information)

#bind columns so each coach is associated with the proper team.
bind_cols(coach_links, coach_df) -> coach_df

#extract coach information from the scraped html. 
coach_df |>
  unnest(info)|>
  mutate(info = str_remove_all(info, "View Full Profile"),
         info = str_remove_all(info, "\\n"),
         coach_name = if_else(str_detect(info, "Position"), str_extract(info, ".*(?=Position)"), str_extract(info, ".*(?=Email)")),
         position = if_else(str_detect(info, "Email"), str_extract(info, "(?<=Position).*?(?=Email)"), str_extract(info, "(?<=Position).*?(?=Phone)")),
         email = str_extract(info, "(?<=Email).*?(?=Phone)"),
         phone_number = str_extract(info, "(?<=Phone).*"),
         phone_number = na_if(phone_number, "N/A"))-> coach_df_prepped
```

```{r}
#clean the prepped coach_df_prepped for final tidyness and organization. put first and last name into seperate columns, remove unneeded intermediate columns, clean up team links, ensure consistent formatting across rows. 

coach_df_prepped |>
  mutate(phone_number = str_remove_all(phone_number, "[\\(\\)]"),
         phone_number = str_replace_all(phone_number, " ", "-"),
         team_link = str_remove(coach_link, "/coaches"))|>
  separate(coach_name, into = c("first_name", "last_name"), sep = " ", extra = "merge", fill = "right")|>
  select(team_name, first_name, last_name, position, email, phone_number, age_group, state, level, team_link)|>
  mutate(across(everything(), str_squish)) -> coach_df_cleaned
```

```{r}
#export as CSV. 

write_csv(coach_df_cleaned, "beverly_bandits_coaches_info.csv")
```

